POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "Song 1",
    "artists": [1, 2],
    "releaseDate": "2021-02-01",
    "duration": "02:10"
}

###

GET http://localhost:3000/songs

###

GET http://localhost:3000/songs/32


###

DELETE http://localhost:3000/songs/3

###

GET http://localhost:3000/songs?page=2&limit=2

