GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImVtYWlsIjoiYnJ1bm9sZW1vc0BiYi5jb20uYnIiLCJhcnRpc3RJZCI6NCwiaWF0IjoxNzQxMzk5NDQ5LCJleHAiOjE3NDE0ODU4NDl9.zhrw7OLUwTE_liRktP8M2iSLD0FIKYUtOWnRiv3t4Rs


###

GET http://localhost:3000/is-artist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImVtYWlsIjoiYnJ1bm9sZW1vc0BiYi5jb20uYnIiLCJhcnRpc3RJZCI6NCwiaWF0IjoxNzQxMzk5NDQ5LCJleHAiOjE3NDE0ODU4NDl9.zhrw7OLUwTE_liRktP8M2iSLD0FIKYUtOWnRiv3t4Rs



###

POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "Song 1",
    "artists": [1, 2],
    "releaseDate": "2021-02-01",
    "duration": "02:10"
}

###

GET http://localhost:3000/songs

###

GET http://localhost:3000/songs/32


###

DELETE http://localhost:3000/songs/3

###

GET http://localhost:3000/songs?page=2&limit=2

###

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "Bruno",
    "lastName": "Ramos Lemos",
    "email": "brunolemos@bb.com.br",
    "password": "123456"
}

###

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "brunolemos@bb.com.br",
    "password": "123456"
}